# Generated by Django 5.1.3 on 2024-12-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("pronunciation", models.CharField(max_length=100)),
                ("meaning", models.TextField()),
                ("audio_path", models.CharField(max_length=255)),
                ("POS", models.CharField(max_length=50)),
                (
                    "Lv",
                    models.CharField(
                        choices=[
                            ("1", "N1"),
                            ("2", "N2"),
                            ("3", "N3"),
                            ("4", "N4"),
                            ("5", "N5"),
                        ],
                        max_length=2,
                    ),
                ),
                ("views", models.IntegerField(default=0)),
            ],
        ),
    ]
