# Generated by Django 5.1.3 on 2024-12-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_todayword"),
    ]

    operations = [
        migrations.AddField(
            model_name="todayword",
            name="blank_word",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="todayword",
            name="today_Lv",
            field=models.CharField(
                choices=[
                    ("1", "N1"),
                    ("2", "N2"),
                    ("3", "N3"),
                    ("4", "N4"),
                    ("5", "N5"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="todayword",
            name="today_POS",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
