# Generated by Django 5.1.3 on 2025-04-12 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_todayword_blank_word_todayword_today_lv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("grid", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PuzzleWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clue", models.TextField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("across", "가로"), ("down", "세로")], max_length=10
                    ),
                ),
                ("start_x", models.IntegerField()),
                ("start_y", models.IntegerField()),
                (
                    "dictionary_entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dictionary.dictionary",
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="dictionary.puzzle",
                    ),
                ),
            ],
        ),
    ]
