# Generated by Django 5.1.3 on 2025-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_puzzle_puzzleword'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='romaji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
